# Generated by Django 4.1 on 2023-04-14 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='NOMBRE', max_length=30)),
                ('Apellido', models.CharField(default='APELLIDO', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(default='USERNAME', max_length=30)),
                ('Contrasena', models.CharField(default='PASSWORD', max_length=30)),
                ('RolUsuario', models.CharField(default='ROL', max_length=512)),
                ('NoCelular', models.CharField(default='999999999', max_length=11)),
                ('FechaIngreso', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(default='NOMBREPRODUCTO', max_length=30)),
                ('Codigo', models.CharField(default='CODIGO', max_length=30)),
                ('PrecioCompra', models.FloatField(default=0.0)),
                ('PrecioVenta', models.FloatField(default=0.0)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tienda.datosusuario')),
            ],
        ),
    ]
